using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SimPle.Domain.Friends;
using SimPle.Domain.Users;

namespace SimPle.Infrastructure.Persistence.Configurations;

public sealed class FriendshipConfiguration : IEntityTypeConfiguration<Friendship>
{
    public void Configure(EntityTypeBuilder<Friendship> builder)
    {
        builder.ToTable("friendships", t =>
        {
            t.HasCheckConstraint("ck_no_self_friendship", @"""RequesterId"" != ""AddresseeId""");
        });

        builder.HasKey(f => f.Id);
        builder.Property(f => f.Status).HasConversion<string>().HasMaxLength(16).IsRequired();
        builder.Property(f => f.SentAt).IsRequired();
        builder.Property(f => f.AcceptedAt);
        builder.Property(f => f.EndedAt);
        builder.Property(f => f.EndReason).HasConversion<string>().HasMaxLength(16);
        builder.Property(f => f.TransitionActorId);
        builder.Property(f => f.NextRequestAllowedAt);

        // Monotonic per-relationship event version and request-cycle counter (server-owned, never client-set).
        builder.Property(f => f.DomainVersion).IsRequired().HasDefaultValue(1L);
        builder.Property(f => f.RequestCycleId).IsRequired().HasDefaultValue(1);

        // Npgsql row-version pattern: uint property mapped to xmin (optimistic concurrency token).
        builder.Property(f => f.Version).IsRowVersion();

        // Keyset cursor indexes: requests list is (SentAt DESC, Id DESC) filtered by actor + status.
        // The leading (actor, Status) prefix also serves the existing actor/status lookups, so no separate
        // two-column indexes are needed.
        builder.HasIndex(f => new { f.AddresseeId, f.Status, f.SentAt, f.Id })
            .IsDescending(false, false, true, true)
            .HasDatabaseName("ix_friendships_addressee_status_sentat_id");
        builder.HasIndex(f => new { f.RequesterId, f.Status, f.SentAt, f.Id })
            .IsDescending(false, false, true, true)
            .HasDatabaseName("ix_friendships_requester_status_sentat_id");

        // CASCADE both FKs — PostgreSQL supports multiple cascade paths to the same table.
        builder.HasOne<User>().WithMany().HasForeignKey(f => f.RequesterId).OnDelete(DeleteBehavior.Cascade);
        builder.HasOne<User>().WithMany().HasForeignKey(f => f.AddresseeId).OnDelete(DeleteBehavior.Cascade);

        // NOTE: The LEAST/GREATEST unordered-pair unique expression index cannot be generated by EF; it is
        // created in migration 20260627154911_AddFriendsAndBlocks (ix_friendships_unordered_pair) and left
        // in place by the corrective migration.
    }
}
