using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SimPle.Domain.Games;

namespace SimPle.Infrastructure.Persistence.Configurations;

public sealed class GameConfiguration : IEntityTypeConfiguration<Game>
{
    public void Configure(EntityTypeBuilder<Game> builder)
    {
        builder.ToTable("games", t =>
        {
            t.HasCheckConstraint("ck_games_min_players", "\"MinPlayers\" >= 1 AND \"MinPlayers\" <= \"MaxPlayers\"");
            t.HasCheckConstraint("ck_games_duration_bounds", "\"EstimatedDurationMinMinutes\" <= \"EstimatedDurationMaxMinutes\"");
            t.HasCheckConstraint("ck_games_draft_retired_not_featured",
                "(\"Lifecycle\" <> 'Draft' AND \"Lifecycle\" <> 'Retired') OR \"FeaturedRank\" IS NULL");
        });

        builder.HasKey(g => g.Id);

        builder.Property(g => g.Slug).IsRequired();
        builder.Property(g => g.Name).IsRequired();
        builder.Property(g => g.Summary).IsRequired();
        builder.Property(g => g.RulesSummary).IsRequired();
        builder.Property(g => g.Category).IsRequired();
        builder.Property(g => g.Difficulty).HasConversion<string>().HasMaxLength(16).IsRequired();
        builder.Property(g => g.Lifecycle).HasConversion<string>().HasMaxLength(16).IsRequired();
        builder.Property(g => g.LifecycleVersion).IsRequired();
        builder.Property(g => g.ArtToken).IsRequired();
        builder.Property(g => g.ArtColorA).IsRequired();
        builder.Property(g => g.ArtColorB).IsRequired();
        builder.Property(g => g.ArtAltText).IsRequired();
        builder.Property(g => g.ManifestVersion).IsRequired();

        // Npgsql row-version pattern: uint property mapped to xmin (optimistic concurrency token).
        builder.Property(g => g.Version).IsRowVersion();

        builder.HasIndex(g => g.Slug).IsUnique();

        // Default order: (FeaturedRank NULLS LAST, SortOrder, Slug) — plain ascending index; Postgres's
        // default NULLS LAST for ASC already matches the intent, no raw SQL needed.
        builder.HasIndex(g => new { g.FeaturedRank, g.SortOrder, g.Slug }).HasDatabaseName("ix_games_default_order");

        // Alternate-sort indexes.
        builder.HasIndex(g => new { g.Name, g.Slug }).HasDatabaseName("ix_games_name_slug");
        builder.HasIndex(g => new { g.Difficulty, g.Slug }).HasDatabaseName("ix_games_difficulty_slug");
        builder.HasIndex(g => new { g.EstimatedDurationMinMinutes, g.Slug }).HasDatabaseName("ix_games_duration_slug");

        builder.HasMany(g => g.Tags)
            .WithOne()
            .HasForeignKey(t => t.GameId)
            .OnDelete(DeleteBehavior.Cascade);
        builder.Navigation(g => g.Tags).UsePropertyAccessMode(PropertyAccessMode.Field);

        builder.HasMany(g => g.Capabilities)
            .WithOne()
            .HasForeignKey(c => c.GameId)
            .OnDelete(DeleteBehavior.Cascade);
        builder.Navigation(g => g.Capabilities).UsePropertyAccessMode(PropertyAccessMode.Field);

        // NOTE: ux_games_featured_rank_one (partial unique index on FeaturedRank = 1) cannot be generated by
        // EF; it is added as raw SQL in the AddGameCatalog migration.
    }
}
